mash-up-kr/mash-up-admin-fe

src/styles/resetCss.ts
=> resetCss를 recruit과 동기화

.github/CODEOWNERS
- 매번 리뷰 요청하는게 귀찮아서 Code Owner를 추가했습니다
- 리뷰 자동으로 요청됨 + Code Owner외엔 수정 불가능 (이건 사실 필요한지 잘 모르겠...)
- PR 만들면 이렇게 자동으로 리뷰 요청 됩니당 (이 PR 머지된 시점부터)
=> Code Owner 추가

@types/custom-types/emotion.d.ts, src/App.tsx, src/styles/colors.ts, src/styles/font.ts, src/styles/fonts.ts, src/styles/index.ts, src/styles/theme.ts
- colors, font (typography인데 디자인팀이랑 용어 맞추려고 font라고 지었어요) 에 대한 디자인 시스템(?) 을 추가했습니다.
- 사용방법은 다음과 같습니다.
```typescript
const Title = styled.div`
color: ${Colors.gray10};
${({ theme }) => theme.font.kr_46_bold};
`
```
1. 첨 알았는데 font-weight: ${number} 속성이 IE에선 지원이 안된다고 하더라구요, emotion이 알아서 바꿔주겠죠??
2. 민수형, 용재형이랑 이야기를 했을 때 font에 대한 것들을 믹스인 방식처럼 만들까, themeProvider로 만들까 오랫동안 이야기 했는데 결론은 themeProvider로 났습니다. 이에 대한 @HaJunRyu @Baek2back 의 생각이 궁금하네여
3. styles/* 파일들도 index 로 묶어서 export 할지??
4. 네이밍을 카멜로 가져가기로 했는데 요것도 카멜로 하는게 맞을지?? `kr22Medium` 이런 너무 이상한거 같아서 일단 스네이크로 만들었어여
- 신규 기능 추가
=> 디자인 시스템 추가

@types/custom-types/emotion.d.ts, src/styles/colors.ts, src/styles/theme.ts
- 카톡에서 논의한 결과 color도 theme를 통해 사용해서 쓰는게 좋은거 같다는 의견으로 모아져 해당 방향성으로 변경하였습니다.
- theme 값이 복수인게 맞는 표현인거 같아 font에서 fonts로 변경했습니다.
theme 쓸 때 어떻게 쓸지?
1. 
```typescript
const A = styled.div`
${({ theme }) => {
return {
${theme.fonts.kr.medium13}
color: theme.colors.gray10,
};
}}
...
`;
```
2.
```typescript
const A = styled.div`
color: ${({theme}) => theme.colors.gray10};
${({theme}) => theme.fonts.kr.medium13};
...
`;
```
이렇게 두가지 방법이 있을거 같은데 정하고 가면 좋을거 같네여 
props 하나로 처리할지, css 프로퍼티 별로 추가하는게 좋을지 (추후에 colors 외 뭔가 더 들어올수도 있기 떄문에)
- 신규 기능 추가
=> Feat: color도 theme를 통해 사용하도록 추가

src/components/common/ToggleButton/ToggleButton.component.tsx, src/components/common/ToggleButton/ToggleButton.stories.tsx, src/components/common/ToggleButton/ToggleButton.styled.ts, src/components/common/index.ts
=> ToggleButton 컴포넌트 추가

src/assets/svg/checkbox-checked.svg, src/components/common/Checkbox/Checkbox.component.tsx, src/components/common/Checkbox/Checkbox.stories.tsx, src/components/common/Checkbox/Checkbox.styled.ts, src/components/common/index.ts
=> Checkbox 컴포넌트 추가 

src/components/common/Checkbox/Checkbox.component.tsx, src/components/common/Checkbox/Checkbox.styled.ts, src/components/common/RadioButton/RadioButton.component.tsx, src/components/common/RadioButton/RadioButton.stories.tsx, src/components/common/RadioButton/RadioButton.styled.ts, src/components/common/ToggleButton/ToggleButton.component.tsx, src/components/common/ToggleButton/ToggleButton.styled.ts, src/components/common/index.ts
=> RadioButton 컴포넌트 추가

src/components/common/DatePicker/DatePicker.component.tsx, src/components/common/Pagination/PageButtonList/PageButtonList.component.tsx, src/utils/array.test.ts, src/utils/array.ts, src/utils/index.ts
- rangeArray 유틸 함수 추가 및 적용
- 신규 기능 추가
- 리팩토링
=> rangeArray 유틸 함수 추가

package.json
- build scripts 변경
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> build scripts 변경

package.json
- build scripts 변경 (main <- develop) 
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> build scripts 변경 (main <- develop) 

package.json
- Build script 수정
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> Build script 수정

src/App.tsx, src/api/index.ts, src/api/team.ts, src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx, src/components/common/Select/Select.component.tsx, src/components/common/ToggleButton/ToggleButton.component.tsx, src/pages/ApplicationFormControl/ApplicationFormControl.page.tsx, src/pages/ApplicationFormControl/ApplicationFormControl.styled.ts, src/store/index.ts, src/store/team.ts, src/styles/resetCss.ts, src/types/dto/applicationForm.ts, src/types/dto/index.ts, src/types/dto/team.ts
- teams 정보 서버로 부터 받아오도록 추가
- 지원설문지 팀 선택할 수 있게 추가 
- 글자수 제한 안나타나는 버그 수정 & 숫자만 받도록 변경
- 질문추가할떄 서버 전송되는 버그 수정
- 신규 기능 추가
- 버그 수정
=> 지원설문지 팀 선택할 수 있게 추가 

src/App.tsx, src/api/applicationForm.ts, src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.component.tsx, src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
- 지원서 설문지 삭제 기능 추가
- 로그인되어있지 않은경우 로그인페이지로 이동하도록 변경
- 신규 기능 추가
=> 지원서 설문지 삭제 기능 추가

src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.component.tsx, src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx, src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts, src/components/common/Checkbox/Checkbox.component.tsx, src/components/common/ModalWrapper/ModalWrapper.component.tsx, src/components/common/ModalWrapper/ModalWrapper.styled.ts, src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
- 모달 스타일 수정
- 지원서 설문지 미리보기 추가
- 지원서 설문지 생성안되는 버그 수정
- 신규 기능 추가
=> 지원설문지 미리보기 추가

src/App.tsx
-
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> develop to main

src/App.tsx, src/components/ApplicationForm/ApplicationFormSection/ApplicationFormSection.component.tsx, src/components/ApplicationForm/ApplicationFormSection/ApplicationFormSection.styled.ts, src/constants/paths.ts, src/hooks/index.ts, src/hooks/useUnmount.ts, src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx, src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx, src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx, src/utils/index.ts, src/utils/request.ts
- api 콜, 페이지 이동 등 액션에 대해서 함수 추가 (추후 PR 본문 더 자세히 작성하겠습니다 죄송합니다 ㅠ)
- 신규 기능 추가
=> 행동에 대한 redirect, 액션 추가

src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx, src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx, src/components/common/ModalWrapper/ModalWrapper.component.tsx, src/components/common/Pagination/PagingSizeSelector/PagingSizeSelector.tsx, src/components/common/Select/Select.component.tsx, src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx, src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx, src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
-
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> 지원서 설문지 생성 수정 삭제 전 확인 모달띄우도록 추가

src/components/common/Table/Table.styled.ts
- Table body 호버시 우측 영역만 느리게 색상이 변경되는 이슈 해결
- Table body 쪽에 스크롤을 가리고 있다가 서서히 보이게 하려고 주었던 transition 속성 제거
- 버그 수정
=> QA 2차 대응 (v0.0.1) - minsour

src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx, src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts, src/components/common/Checkbox/Checkbox.component.tsx
- 지원서 미리보기 모달에 개인정보처리방침 url 추가
- CheckBox의 label React.ReactNode로 변경 (스타일 추가를 위해)
- 신규 기능 추가
=> 지원서 미리보기 모달에 개인정보처리방침 url 추가

src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
=> 개인정보 처리방침 스타일 수정

src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx, src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
=> Qa Release/v0.0.1 - 5차

src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx, src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
- 지원설문지 미리보기 생년월일, 거주지, 소속 필드 추가
- 이메일 수정 설명 삭제
- 신규 기능 추가
=> 지원설문지 미리보기 생년월일, 거주지, 소속 필드 추가

src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
- 지원설문지 미리보기 소속 필드에 빠트린 required 속성 추가
- 버그 수정
=> 지원설문지 미리보기 소속 필드에 빠트린 required 속성 추가

src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx, src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
- CustomTextarea 스타일 제거
- 버그 수정
=> 실행 안되는 에러 해결

public/index.html
- description meta tag 추가
- Qa Release/v0.3.0
- 신규 기능 추가
- 배포 관련
=> Qa Release/v0.3.0

src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx, src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx, src/components/common/SmsSendModalDialog/SmsSendModalDialog.stories.tsx, src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
- resolve #136 
- SmsSendModal에 실패인원 재발송 케이스 추가
- 신규 기능 추가
- 리팩토링
=> 필요한 커밋 revert 및 SmsSendModal 실패인원 재발송 케이스 추가

src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx, src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx, src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx, src/store/login.ts, src/types/dto/adminMember.ts
- message 전송 api 에서 applicationId 를 담아 보냈던걸 data. applicant.applicantId로 변경
- SmsSendModal confirmButton disabled 제거
- phoneNumber 항목 추가
- 리팩토링
- 버그 수정
=> 문자 발송 API Body 에 잘못 들어간 값 변경

src/components/common/Table/Table.styled.ts, src/pages/ApplicationList/ApplicationList.page.tsx, src/pages/ApplicationList/ApplicationList.styled.ts, src/utils/array.ts
- 지원서 내역 페이지에 일괄 합격여부 변경 모달 추가
- 중복된 요소를 제거하는 uniqArray 유틸 함수 추가
- 신규 기능 추가
=> 지원서 내역 페이지에 일괄 합격여부 변경 모달 추가

src/components/common/Table/Table.test.tsx, src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx, src/pages/ApplicationList/ApplicationList.page.tsx, src/types/dto/application.ts
- 지원 일시 기준을 updatedAt에서 submittedAt 으로 변경
- 리팩토링
=> 지원 일시 기준을 updatedAt에서 submittedAt 으로 변경

src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
- recruit validate 로직 없는 필드에 대해서 #155 추가 작업
- 리팩토링
- 버그 수정
=> 인적정보에도 entity unescape 로직을 추가

src/pages/ApplicationList/ApplicationList.page.tsx, src/pages/ApplicationList/ApplicationList.styled.ts, src/store/modal.ts
- "#" 제거, 지원서 리스트 버튼 disable 처리, 에셀 export시 각 플랫폼 모든 인원을 내보내도록 처리
- 신규 기능 추가
- 리팩토링
- 버그 수정
=> # 제거, 지원서 리스트 버튼 disable 처리, 엑셀 export시 각 플랫폼 모든 인원을 내보내도록 처리

src/store/modal.ts
- window.history.replaceState 에 search param을 고려하도록 처리
- 모달 취소에 따른 배경화면 변화 해결
- SMS 발송 상세내역 선택시 목록 인덱스가 달라지는 현상 해결
- 새로고침, 상세 진입 후 뒤로가기 하면 search param이 사라지던 이슈 해결
- 리팩토링
- 버그 수정
=> QA 4차 대응 (v0.4.0) - dididy 

src/components/common/SearchOptionBar/SearchOptionBar.component.tsx, src/hooks/usePagination.ts, src/pages/ApplicationFormList/ApplicationFormList.page.tsx, src/pages/ApplicationList/ApplicationList.page.tsx, src/pages/SmsSendingList/SmsSendingList.page.tsx
- usePagination에서 usingSearchParams 예외 처리 추가
- placeholder 오타 수정
- 버그 수정
=> QA 5차 대응 (v0.4.0) - minsour

src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx, src/components/common/Toast/Toast.styled.ts
- 토스트 z-index 적용 이슈 해결
- 인터뷰 시간 50분으로 가정하고 수정
- isScreeningPassed 변수에 INTERVIEW_TO_BE_DETERMINED 케이스 추가
- 신규 기능 추가
- 리팩토링
- 버그 수정
=> QA 7차 대응 (v0.4.0) - dididy 

src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx, src/pages/ApplicationList/ApplicationList.page.tsx
- ChangeResultModalDialog에서 서류 합격 케이스를 예외 처리
- 신규 기능 추가
- 리팩토링
=> QA 10차 대응 (v0.4.0) - dididy 

src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
This reverts commit 44288f2c7c090adaf2a64a2c4a9be72d39a001fa.
-
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> Revert "Fix: ChangeResultModalDialog에서 서류 합격 케이스를 예외 처리 한다"

src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.styled.ts, src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx, src/components/ApplicationDetail/MessageListPanel/MessageListPanel.stories.tsx, src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx, src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.stories.tsx, src/types/dto/sms.ts
- 리스트에서 합격 여부 반영 후 상세에서 상태 변경이 되지 않는 이슈 해결
- 지원서 상세 sms 발송 내역에 sentAt 을 고려하여 리팩토링
- 버그 수정
=> QA 13차 대응 (v0.4.0) - dididy

src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx, src/pages/ApplicationList/ApplicationList.page.tsx
- 지원설문지 상세 SMS 발송내역 발송 내용 entity 처리와 줄바꿈을 적용
- 지원서 내역 합격여부, 사용자 확인 여부 필터 동작을 정상화
- 버그 수정
=> QA 15차 대응 (v0.4.0) - dididy

src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx, src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.component.tsx, src/components/common/Button/Button.component.tsx, src/components/common/Button/Button.styled.ts, src/components/common/ModalWrapper/ModalWrapper.component.tsx, src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx, src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx, src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx, src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx, src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
- Button에 isLoading 케이스를 추가하고 api 요청시 추가 요청 방지
- 신규 기능 추가
- 리팩토링
=> Button에 isLoading 케이스를 추가하고 api 요청시 추가 요청 방지

src/components/common/Layout/Layout.component.tsx, src/pages/ActivityScoreDetail/ActivityScoreDetail.page.tsx, src/pages/ActivityScoreList/ActivityScoreList.page.tsx, src/pages/ActivityScoreList/ActivityScoreList.styled.ts
- 활동점수 상세 레이아웃 배경색 없는 이슈 수정
- url 변경되면서 놓쳤어요 ㅠ
- 활동점수 상세페이지 headline 이름 수정
- 활동점수 이름 클릭했을 떄 상세로 이동하도록 추가
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> 활동점수 이름 클릭했을 떄 상세로 이동하도록 추가

src/App.tsx, src/api/generation.ts, src/api/index.ts, src/components/common/Select/Select.component.tsx, src/pages/ActivityScoreList/ActivityScoreList.page.tsx, src/store/generation.ts, src/store/index.ts, src/types/dto/generation.ts, src/types/dto/index.ts
- Select 컴포넌트에 defaultValue가 동적으로 변경될 때 적용되지 않아서 수정
- 기수 정보 api 연동
- 신규 기능 추가
- 버그 수정
=> 기수정보 api 연동

src/api/index.ts, src/api/member.ts, src/components/common/Select/Select.component.tsx, src/pages/ActivityScoreList/ActivityScoreList.page.tsx, src/store/member.ts, src/types/dto/index.ts, src/types/dto/member.ts
- 활동점수 목록 (멤버) api 연동
- Select defaultValue 관련 로직 롤백
- 기존 로직에서 오작동하는 부분이 있어서 일단 롤백
- 관련 커밋: a7958e28517aab44786d291857864eec06bf4303
- 활동점수 (멤버) 플랫폼통해서도 검색되게 추가
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> 활동점수 목록 api 연동

src/components/ActivityScore/ScoreCard/ScoreCard.styled.ts, src/components/common/DatePicker/DatePicker.component.tsx, src/components/common/ModalWrapper/ModalWrapper.styled.ts, src/components/common/Select/Select.component.tsx, src/components/common/Table/Table.component.tsx, src/components/common/Table/Table.styled.ts, src/components/common/TeamNavigationTabs/TeamNavigationTabs.component.tsx, src/components/modal/ActivityScoreModalDialog/ActivityScoreModalDialog.component.tsx, src/components/modal/ActivityScoreModalDialog/ActivityScoreModalDialog.styled.ts, src/components/modal/ApplyActivityScoreModalDialog/ApplyActivityScoreModalDialog.component.tsx, src/components/modal/ApplyActivityScoreModalDialog/ApplyActivityScoreModalDialog.styled.ts, src/hooks/index.ts, src/hooks/useMyTeam.ts, src/pages/ActivityScoreDetail/ActivityScoreDetail.page.tsx, src/pages/ActivityScoreDetail/ActivityScoreDetail.styled.ts, src/pages/ActivityScoreList/ActivityScoreList.page.tsx, src/pages/ActivityScoreList/ActivityScoreList.styled.ts, src/store/login.ts, src/utils/number.ts
https://www.notion.so/TC-QA-44297917100b40d99629392740922265 기준으로 놓친 부분들을 추가 / 수정 하였습니다
- 신규 기능 추가
- 버그 수정
=> 활동점수 어드민 qa 입고전 셀프 qa 작업 내용

.github/CODEOWNERS
- 코드 오너를 현재 프로젝트 인원에 맞춰 수정합니다.
- develop쪽에도 했는데 main쪽에 푸시되어야 적용되는거 같아서 main쪽에도 작업하려해여
=> chore: 코드오너 추가

src/App.tsx, src/components/common/Button/Button.component.tsx, src/pages/LoginPage/LoginPage.page.tsx
* 디자인쪽 요청사항에 의해 Button이 loading 상태일 경우 텍스트 안보여주게 하고, 스피너만 돌게 수정
* 로그인 중일떄 스피너 추가
* team api가 권한이 있는 사람만 요청할 수 있는데 비로그인 상태에서 로그인 페이지에서 요청하는 이슈가 있어서 수정
- 신규 기능 추가
- 버그 수정
=> 로그인 스피너 추가, 비로그인 상태에서 team api 요청하는 이슈 수정

src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.styled.ts, src/components/common/Input/Input.styled.ts, src/components/common/Textarea/Textarea.styled.ts
- 지원설문지 제목이 2줄이상으로 넘어갈 때 필수 점 표시 짤리는 이슈 수정
- 지원서 답변 연속된 문자열일 때 줄바꿈 되지 않는 이슈 수정
- 버그 수정
=> 지원서, 지원서 설문지 디자인 이슈 수정

src/api/schedule.ts, src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx, src/components/Schedule/ContentTemplate/ContentTemplate.component.tsx, src/components/Schedule/ScheduleTemplate/ScheduleTemplate.component.tsx, src/components/Schedule/ScheduleTemplate/ScheduleTemplate.styled.ts, src/components/Schedule/SessionTemplate/SessionTemplate.component.tsx, src/components/common/Input/Input.component.tsx, src/components/common/Select/Select.component.tsx, src/components/common/Select/Select.styled.ts, src/components/fields/DatePickerField/DatePickerField.component.tsx, src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx, src/constants/paths.ts, src/pages/CreateSchedule/CreateSchedule.page.tsx, src/pages/CreateSchedule/CreateSchedule.styled.ts, src/pages/ScheduleList/ScheduleList.page.tsx, src/pages/ScheduleList/ScheduleList.styled.ts, src/types/dto/schedule.ts, src/utils/date.ts, src/utils/type.ts
- 스케쥴 등록 api 연동
- Select, DatePicker ref를 주입함으로써 react-hook-form 필드로 쓸 때 에러가 날 경우 autoFocus 하도록 함
- 이를 위해 Select의 wrapper를 div에서 input 으로 변경
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
=> 스케줄 생성 api 연동 

src/api/schedule.ts, src/components/common/Header/Header.component.tsx, src/pages/ScheduleDetail/ScheduleDetail.page.tsx, src/pages/UpdateSchedule/UpdateSchedule.page.tsx
- 스케줄 삭제 기능 추가
- 지금 삭제 api가 제대로 작동을 안해서 서버에서 고친 후 확인 후 머지를 하면 될거 같습니당
- 신규 기능 추가
=> 스케줄 삭제 기능 추가

.github/CODEOWNERS
- 인원 변경에 따라 코드오너를 수정합니당
- 그동안 즐거웠어여~!
=> chore: 코드오너 수정

src/pages/ActivityScoreDetail/ActivityScoreDetail.page.tsx
- 활동점수 상세 테이블 열 너비 및 제목 수정
- 점수 추가 버튼 텍스트 크기 조정
- 기능 수정
=> 활동점수 상세 스타일 수정

src/components/common/LNB/LNB.styled.ts
=> LNB x scroll 제거

src/components/common/Editor/Editor.component.tsx, src/pages/UpdatePlatformRecruit/UpdatePlatformRecruit.page.tsx
Reverts mash-up-kr/mash-up-admin-fe#277
=> Revert "모집공고 에디터 QA 반영"

src/pages/UpdatePlatformRecruit/UpdatePlatformRecruit.page.tsx
- 브랜딩 회원의 모집공고 플랫폼 선택이 안 되는 버그를 수정합니다.
- 버그 수정
=> 브랜딩 회원의 모집공고 플랫폼 선택 버그 수정

src/components/modal/CreateHelperAdminMemberDialog/CreateHelperAdminMemberDialog.component.tsx
- 사용자 요청으로 필드명을 이름에서 아이디로 변경
- 리팩토링
- 버그 수정
=> Fix: 필드명을 이름에서 아이디로 변경한다

src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx, src/pages/ApplicationList/ApplicationList.page.tsx
- 지원서 목록 최신 데이터 로드
- 지원서 상세 면접 일시 셀렉트 버그 수정
- 리팩토링
- 버그 수정
=> 지원서 목록 최신 데이터 로드, 지원서 상세 면접 일시 셀렉트 버그 수정

src/components/Schedule/ScheduleTemplate/ScheduleTemplate.component.tsx
=> 임시 key값 처리

src/components/Schedule/ScheduleTemplate/ScheduleTemplate.component.tsx, src/components/ScheduleDetail/ScheduleInfoList/ScheduleInfoList.component.tsx, src/pages/ScheduleDetail/ScheduleDetail.page.tsx, src/types/dto/schedule.ts, src/utils/schedule.ts
- 플랫폼 스케줄인 경우 공지 추가 작업
- 신규 기능 추가
=> 플랫폼 스케줄인 경우 공지 추가 작업

src/components/Schedule/ScheduleTemplate/ScheduleTemplate.component.tsx
- 개인 계정 키로 관리되던 카카오 API 키를 브랜딩 계정 애플리케이션 키로 변경합니다.
- vercel 환경변수 KAKAO_KEY 추가 완료
- 신규 기능 추가
=> 브랜딩 계정 카카오 애플리케이션 키로 변경

webpack/webpack.base.js
- Vercel 배포 시에 환경 변수를 제대로 읽지 못하는 이슈가 있어 dotenv 설정을 수정하여 테스트합니다.
- 버그 수정
=> dotenv 설정 수정

src/components/modal/ApplyActivityScoreModalDialog/ApplyActivityScoreModalDialog.component.tsx
- 15기 활동 점수 정책에 맞게 활동 점수 항목을 수정 및 제거 사항 배포
- 배포 관련
=> 15기 활동 점수 정책에 맞게 활동 점수 항목을 수정 및 제거 사항 배포
