mash-up-kr/mash-up-admin-fe

- .gitignore
- package.json
- tsconfig.json
지난 번 admin 회의에서 브라우저 지원을 위해 ts-loader를 사용할 경우 target을 es5로 낮추자는 의견을 반영했습니다.
하는김에 recruit tsconfig과 sync를 맞추었고 type-check와  build script를 적절하게 수정했습니다.
* forceConsistentCasingInFileNames 추가
* ~~module esnext로 변경~~ // 빌드 에러 발생
* target es5로 변경
* lib 추가("dom", "dom.iterable", "esnext")
* noEmit 추가(true)
* isolatedModules 추가(true)
* ~~jsx preserve로 변경~~ // jest 에러 발생
* incremental 추가(true)
* exclude 제거
* outDir 제거
* 빌드시 타입체크 활성화
* tsconfig.tsbuildinfo gitignore에 추가
- 리팩토링
> tsconfig target es5로 수정 및 recruit과 동기화

- src/components/common/Layout/Layout.component.tsx
- src/components/common/Layout/Layout.styled.ts
main 에 width를 고정하면 배경색이 width 기준으로 적용되어서 하위  section 계층을 하나 더 추가하였습니다.
아래 기준에 맞춰서 'login', 'application/', 'application-form/' 이 pathname에 포함되면 isBackgroundGray 로 배경 색을 선택하도록 처리했습니다.
- 로그인
- /login - gray10
- 지원서 내역
- /application - white
- 지원서 상세
- /application/:id - gray10
- SMS 발송 내역
- /sms - white 
- 지원 설문지 내역
- /application-form - white
- 지원 설문지 상세
- 상세
- /application-form/:id - gray10
- 추가
- /application-form/create - gray10
- 수정
- /application-form/update/:id - gray10
- not found
- /404 - 미정
- 신규 기능 추가
- 리팩토링
- 버그 수정
- 문서 업데이트
- 배포 관련
> pathname에 따라 배경 색을 white, gray10 으로 각각 토글되도록 처리

- src/App.tsx
- src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
- 지원서 설문지 상세페이지 가지지 않는 버그 수정
- 상위 요소에 Form이 없는데 Form에서 값을 가져와서 ApplicationFormPreview에서 오류가 나고 있었음.
- App.tsx 안쓰는 값 있어서 커밋이 안돼서 수정 
- 버그 수정
> 지원서 설문지 상세페이지 가지지 않는 버그 수정

- src/components/common/AlertModalDialog/AlertModalDialog.component.tsx
- src/components/common/AlertModalDialog/AlertModalDialog.stories.tsx
- src/components/common/ModalViewer/ModalViewer.component.tsx
- src/components/common/ModalViewer/ModalViewer.stories.tsx
- src/store/modal.ts
- ModalViewer 스토리를 참고해서 사용하시면 됩니다.
- 새로고침시 AlertModalDialog는 유지되지 않도록 처리했습니다
- confirm button 클릭시 handler를 props로 넣을 수 있도록 처리했습니다.
- 신규 기능 추가
- 리팩토링
- 버그 수정
> AlertModalDialog에 핸들러를 넣고 새로고침시 유지 안되도록 처리

- src/components/common/UserProfile/UserProfile.component.tsx
- src/styles/themes/userProfile.ts
- UserProfile 컴포넌트 내부 Role 객체 내부 값 중 SUBLEADER 에 공백이 있는 이슈가 있어서 이를 처리했습니다.
- 버그 수정
> MASHUP_SUBLEADER 처럼 SUBLEADER에 공백을 제거한다

- src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
- src/components/common/Table/Table.component.tsx
- src/components/common/Table/Table.styled.ts
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationFormList/ApplicationFormList.styled.ts
- src/styles/themes/colors.ts
- 지원서 설문지 내역 페이지 내 테이블에서 미리보기 아이콘 버튼 클릭 시 미리보기가 뜨지 않고 상세 페이지로 넘어가는 이슈 해결
- tr 태그 내부에 미리보기 icon을 포함하는 button이 위치하고 tr과 button 두 요소에 onClick이 걸려있는 상황이었음
button이 클릭되었을 때 tr의 onClick 함수가 실행되는 이슈라서 button onClick에서 stopPropagation()으로 이벤트 버블링의 전파를 막아주려고 하였지만, React에서 stopPropagation이 제대로 동작하지 않는 이슈가 있어 결국 스펙을 변경함
as-is
tr 태그(테이블의 로우)를 클릭하면 상세 페이지로 이동함
: tr, button 두 요소에 이벤트 바인딩
to-be
테이블의 문서명 셀을 클릭해야 상세 페이지로 이동함
: button 에만 이벤트 바인딩
- 지원서 설문지 내역 페이지에서 팀 탭 이동 시 searchWord 초기화되도록 수정
- 신규 기능 추가
- 리팩토링
- 버그 수정
> QA 1차 대응 (v0.0.1) - minsour

- src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
- 글자수 제한 수정했을 때 지원서 폼 저장되지 않는 이슈 수정
- 추적해보니 pattern 에러였고 - 못넣게 하려고 넣은 코드였는데 min으로 예외처리 가능해서 뻄
- 버그 수정
> 글자수 제한 수정했을 때 지원서 폼 저장되지 않는 이슈 수정

- src/components/common/ModalViewer/ModalViewer.component.tsx
- src/components/common/ModalViewer/ModalViewer.stories.tsx
- src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
- src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.component.tsx
- src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.stories.tsx
- src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
- src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.stories.tsx
- src/components/modal/index.ts
- src/store/modal.ts
- 발송인원 상세 리스트, SMS 발송 상세내역 Table 추가 전 베이스 모달 다이얼로그 컴포넌트 추가
- SMS 발송 컴포넌트에 발송인원 상세 리스트 모달 연결
- 신규 기능 추가
> 발송인원 상세 리스트, SMS 발송 상세내역 모달 다이얼로그 베이스 추가

- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.stories.tsx
- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.styled.ts
- 서류 합격을 기준으로 지원설문지 상세 합격여부 Select option을 아래 두가지 경우로 분기처리하도록 함
- 서류 합격이 아닌경우 선택 가능한 옵션 => 미검토, 서류 보류, 서류 불합격, 서류 합격
- 서류 합격인 경우 선택 가능한 옵션 => 서류 합격, 최종 불합격, 최종 합격
- https://deploy-preview-146--affectionate-jones-aa31c6.netlify.app/?path=/story/applicationdetail-application-panel--application-panel-tbd
- 불필요한 선택을 막기위한 용도
- 리팩토링
> 지원설문지 상세 합격여부 Select를 SCREENING_PASSED 기준으로 validate

- src/api/application.ts
- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.stories.tsx
- src/components/common/DatePicker/DatePicker.component.tsx
- src/components/common/DatePicker/DatePicker.stories.tsx
- src/types/dto/application.ts
- DatePicker에서 selected 된 날짜를 년,월,일까지만 비교하게 함
- postUpdateResult url 잘못된 부분을 수정
- useFormContext로 date 값을 읽고 수정하도록 처리
- useForm에 defaultValue 추가
- ApplicationPanel에 isScreening, isShowInterviewSchedule 상태를 분리해서 분기처리
- 인터뷰 이후 절차가 확정된 상황인지, 합격 여부 설정시 면접 일정을 노출해야되는 상황인지를 분리시킴
- 신규 기능 추가
- 리팩토링
- 버그 수정
> ApplicationPanel의 예외사항을 고려하여 리팩토링

- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
- src/utils/date.ts
- dayjs utc 변환시 Z 기준으로 시간이 변환되던 부분 수정
- 버그 수정
> dayjs utc 변환시 Z 기준으로 시간이 변환되던 부분 수정

- src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
- src/components/common/ModalViewer/ModalViewer.component.tsx
- src/components/common/ModalViewer/ModalViewer.stories.tsx
- src/components/common/Pagination/Pagination.component.tsx
- src/components/common/Pagination/Pagination.stories.tsx
- src/components/common/Pagination/PagingSizeSelector/PagingSizeSelector.tsx
- src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
- src/components/common/SmsSendModalDialog/SmsSendModalDialog.stories.tsx
- src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
- src/components/common/Table/Table.component.tsx
- src/components/common/Table/Table.stories.tsx
- src/components/common/Table/Table.styled.ts
- src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
- src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
- src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.stories.tsx
- src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.styled.ts
- src/hooks/usePagination.test.ts
- src/hooks/usePagination.ts
- src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- src/utils/array.ts
- src/utils/string.ts
- SMS 일괄전송 모달 적용
- Pagination, Table 필요한 부분 리팩토링
- paging 할 때 url 안건드릴 수 있는 옵션 추가
- Table 스타일 변경
- 합격 여부 일괄 변경 후 새로고침 하지 않아도 지원서 새로 받아와서 그려주도록 수정
모달 내에 Table을 붙히면서 기존에 지원서 내역 페이지에 Table body에 스크롤이 안생기고 height가 auto로 잡히도록 변경되었습니다.
다음 PR에서 지원서 내역 페이지에 Table 스타일 수정을 다룰 예정입니다.
- 신규 기능 추가
> Application list page에 SMS 일괄전송 모달 적용

- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
- src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
- src/utils/date.ts
- 수정 클릭시 SCREENING_PASSED 일 경우에만 날짜 선택이 나오도록 함
- 인터뷰 결과 발표 이후에 합격 여부 변경을 못하도록 처리
- 케이스를 세밀하게 나누려고 했으나 오히려 운영진이 선택을 실수할 경우 문제가 될 것 같아 인터뷰 결과 발표  이후에만 변경 불가하도록 처리
- 신규 기능 추가
- 버그 수정
> 인터뷰 결과 발표 이후에 합격 여부 변경을 못하도록 처리

- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
- src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
- src/components/common/Table/Table.component.tsx
- src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.component.tsx
- src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- [상세페이지 합격여부] 최종합격 선택지가 빠져있는 이슈 해결
- 지원서가 선택되었을때도 SMS 발송, 합격 여부 변경 cursor가 not-allowed로 되어있는 이슈 해결
- SMS 발송 모달 딤 영역 클릭시 닫히는 동작 제거
- 상세페이지에서 합격 여부 변경시 테이블에 반영 안되는 이슈 임시 해결 #170 
- 신규 기능 추가
- 리팩토링
- 버그 수정
> QA 3차 대응 (v0.4.0) - dididy

- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
- src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
- src/components/common/Table/Table.component.tsx
- src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.component.tsx
- src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
> Qa Release/v0.4.0 - 3차

- src/components/ApplicationForm/ApplicationFormSection/ApplicationFormSection.component.tsx
- src/hooks/index.ts
- src/hooks/useHistory.ts
- src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- useHistory 커스텀 훅 추가
- 이전 path를 가져올 방법이 push 할떄 state로 넣어주는 방법밖에 없는거 같아서, state로 넣어주는 push 함수와 state 체크해서 뒤로가기 해주는 goBack 함수 생성
- 지원서 설문 상세에서 이전 path를 가지고 있을 경우 이전 path로 가고 (query string 유지), 없다면 default로 설정한 url로 이동하도록 수정
- react-router v6로 넘어오면서 `useLocation`에 사용되던 제네릭이 삭제된거 같음.... 그래서 쩔수 없이 assertion했음
- https://github.com/reach/router/issues/414#issuecomment-1003613775
- 신규 기능 추가
- 버그 수정
> QA 12차 대응 (v0.4.0) - mango906

- src/hooks/useConvertToXlsx.ts
- src/pages/ApplicationList/ApplicationList.page.tsx
- 상용에서 처음 지원자 리스트 진입시 xlsx 파일 다운 안되는 이슈 해결
- 버그 수정
> useConvertToXlsx 에서 isLoading에 따라 useEffect이 실행되도록 한다

- src/components/common/Navigation/Navigation.component.tsx
기존에는 pathname이랑 절대적으로 (?) 비교해서 상세 페이지나 수정 페이지에서는 navigation 이 active되어 있지 않는 문제가 있어서 수정하였습니당
- 버그 수정
> 상세페이지에서도 navigation active 되도록 수정

- src/hooks/useConvertToXlsx.ts
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- src/pages/ApplicationList/ApplicationList.styled.ts
- src/pages/SmsSendingList/SmsSendingList.page.tsx
- src/styles/resetCss.ts
- src/styles/themes/button.ts
- 선택된 항목을 엑셀 다운로드 가능하도록 수정
- defaultLine 버튼의 disabled 스타일 수정
- 신규 기능 추가
> 선택된 항목을 엑셀 다운로드 가능하도록 수정

- src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
- src/hooks/useHistory.test.ts
- src/hooks/useHistory.ts
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- src/pages/SmsSendingList/SmsSendingList.page.tsx
- useHistory 훅에 쿼리스트링 유지할지 여부 관련된 훅 추가
- useHistory 테스트코드 추가
- 지원서 상세에서 뒤로가기할 때 필터 유지되도록 변경
- filterValues를 state에서 query string으로 변경되도록 수정
- searchWord를 state에서 query string으로 변경되도록 수정
- 신규 기능 추가
> 지원서 상세에서 뒤로가기할 때 필터 유지되도록 변경

- src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- src/pages/SmsSendingList/SmsSendingList.page.tsx
- SearchOptionBar (상단 검색바) 의 filter가 있는 경우의 수가 하나밖에 없어서, filter값이 컴포넌트 내부에서 관리되고 있었는데, 출첵 앱 기획상 다른 필터 (기수) 가 들어감으로써 화면별로 다른 filter가 있는 요구사항이 생겨서 filter를 외부에서 주입받아 쓰도록 변경하였습니다.
- 변경사항들을 보면 내부에서 관리되고 있는 Option들이 상위 컴포넌트로 이동했고, 나머지 로직은 전체적으로 거의 동일합니당
- 리팩토링
> SearchOptionBar 컴포넌트 filter 외부에서 주입받아 쓰도록 리팩토링

- src/App.tsx
- src/components/common/Header/Header.component.tsx
- src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
- src/constants/paths.ts
- src/pages/AttendanceList/AttendanceList.page.tsx
- src/pages/AttendanceList/AttendanceList.styled.ts
- src/pages/index.ts
출결점수 페이지 UI 추가
Select에서 선택한 기수 정보를 쿼리 스트링에 담고 있는데, 현재 기수에 대한 정보는 쿼리 스트링에 담고 있는게 좋을까요 아니면, 쿼리스트링이 없다면 현재 기수인걸로 간주하는게 좋을까요 ? (구현된 내용은 현재 기수면 쿼리스트링에 담기지 않고, 쿼리스트링이 없다면 현재 기수로 판별)
- 신규 기능 추가
> 출결점수 목록 페이지 UI 추가

- src/components/ActivityScore/ActivityScoreModalDialog/ActivityScoreModalDialog.component.tsx
- src/components/ActivityScore/ActivityScoreModalDialog/ActivityScoreModalDialog.styled.ts
- src/components/ActivityScore/Icon/Icon.component.tsx
- src/components/ActivityScore/index.ts
- src/components/common/ModalWrapper/ModalWrapper.component.tsx
- src/pages/ActivityScoreDetail/ActivityScoreDetail.page.tsx
- src/pages/ActivityScoreDetail/ActivityScoreDetail.styled.ts
- webpack/webpack.base.js
- svgr이 기본적으로 viewBox를 제거하는데, viewBox를 제거함으로써 크기를 조절할 수 없어서, viewBox를 제거하지 않도록 수정
- ModalWrapper 컴포넌트에 confirmButton 옵션만 존재하는 경우도 있어서 cancelButton도 옵셔널하게 변경
- 활동점수 Icon 사이즈 조절할 수 있도록 추가
- 활동점수 상세 모달 UI 추가
- 신규 기능 추가
> 활동점수 상세 모달 UI 추가

- src/components/ActivityScore/ActivityScoreModalDialog/ActivityScoreModalDialog.component.tsx
- src/components/ActivityScore/ActivityScoreModalDialog/ActivityScoreModalDialog.styled.ts
- src/components/ActivityScore/ApplyActivityScoreModalDialog/ApplyActivityScoreModalDialog.component.tsx
- src/components/ActivityScore/ApplyActivityScoreModalDialog/ApplyActivityScoreModalDialog.styled.ts
- src/components/ActivityScore/constants.ts
- src/components/ActivityScore/index.ts
- src/components/ActivityScore/utils.ts
- src/components/common/DatePicker/DatePicker.component.tsx
- src/components/common/DatePicker/DatePicker.styled.ts
- src/components/common/Input/Input.component.tsx
- src/components/common/Input/Input.styled.ts
- src/components/common/RadioButton/RadioButton.component.tsx
- src/components/common/RadioButton/RadioButton.styled.ts
- src/components/fields/DatePickerField/DatePickerField.component.tsx
- src/components/fields/index.ts
- src/pages/ActivityScoreDetail/ActivityScoreDetail.page.tsx
- src/utils/date.ts
- RadioButton 스타일 수정
- RadioButton handleClickButton 옵셔널한 인자로 수정
- DatePicker 컴포넌트 수정
- 스타일 수정
- 날짜선택됨을 기본ㄹ값으로 오늘이 아닌, 비워둘수 있게 수정
- DatePickerField 컴포넌트 추가
- Input Fill 옵션 추가
- 활동점수 적용 모달 ui 추가
- 신규 기능 추가
> 활동점수 적용 모달 UI 추가

- .github/CODEOWNERS
- src/components/Generation/GenerationSelect/GenerationSelect.component.tsx
- src/components/Generation/index.ts
- src/components/common/Layout/Layout.component.tsx
- src/components/common/Layout/Layout.styled.ts
- src/components/common/Select/Select.component.tsx
- src/pages/ActivityScoreList/ActivityScoreList.page.tsx
- src/pages/ActivityScoreList/ActivityScoreList.styled.ts
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- src/pages/ApplicationList/ApplicationList.styled.ts
- src/store/generation.ts
- src/types/dto/application.ts
- src/types/dto/applicationForm.ts
- src/types/dto/member.ts
- src/utils/number.ts
* 기수정보 선택해서 해당 기수의 관련된 데이터 조회하도록 추가
* 해당 로직은 GenerationSelect해서 결정짓도록
* 첨에 url query string으로 하다가 다른 페이지를 가거나 새로고침해도 기수정보를 유지시키기 위해 recoil-persist를 사용해서 localStorage에 넣도록 했어요
* SMS를 제외하고 모든 페이지에 적용
* @sanoopark 코드오너 추가
-
- 신규 기능 추가
> 기수정보 선택할 수 있도록 추가

- src/components/common/Header/Header.component.tsx
- src/hooks/index.ts
- src/hooks/useRefreshSelectorFamilyByKey.ts
- src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
- src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
- 지원서, 지원서 설문지 내역에서 기수정보 변경할 때 페이징 정보 초기화
- 활동점수 페이지 노출 비활성화
- 이번 QA 범위가 아니라 나중에 노출
- useRefreshSelectorFamilyByKey 훅 추가
- 추가, 수정 삭제 시에 내역에 해당하는 selector를 초기화 해야하는데 다른 페이지에선 이미 할당된 selector에 필요한 param을 가지고 있찌 않아서 selectorKey로 리셋시키는 훅
- 지원서 설문지 추가,수정,삭제 후 지원서 설문지 갱신되지 않는 이슈 수정
- 지원서 설문지 수정 후 상새 내역으로 이동할 때 Blocker에 가로막히는 이슈 수정
- Blocker는 페이지를 이탈하시겠습니까? 모달로 생각하면 됨
- 지원서 설문지 추가페이지에도 Blocker 컴포넌트 추가
- 신규 기능 추가
- 버그 수정
> 1.2.0 qa 준비

- src/App.tsx
- src/api/team.ts
- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
- src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
- src/utils/date.ts
- 지원서 합격 여부 변경할 수 없는 이슈 수정
- 날짜 로직이 12기 지원에 맞춰져 있어서 삭제
- 날짜 검증 로직이 필요없을거 같아 삭제
- 최신기수 아닐 경우 지원서 필터 걸리지 않는 이슈 수정
- 지원서 필터의 teamId가 기수별로 다른데 무조건 최신 기수로 가서 조회가 안됨
- useEffect를 써서 해결했는데 더 좋은 방법이 있다면 추천해주셔도 됩니당 (맘에 안들어요 ㅠ)
- 버그 수정
> Qa Release/v1.2.0 - 2차

- src/App.tsx
- src/components/common/Header/Header.component.tsx
- src/components/common/Layout/Layout.component.tsx
- src/constants/paths.ts
- src/pages/ScheduleList/ScheduleList.page.tsx
- src/pages/ScheduleList/ScheduleList.styled.ts
- src/pages/index.ts
- src/types/dto/schedule.ts
- 활동점수 네비게이션에서 다시 노출
- 스케줄 정보 목록 UI 추가
- api 연동은 여기서 하지 않았지만 어차피 rows가 dto기반으로 생성될거라 response dto만 생성해주었어요.
- 스케줄은 qa를 완성되기 전까지 qa를 하지 않기 때문에 develop 대신 별도의 브랜치 feat/schedule로 머지합니다.
- 신규 기능 추가
> 스케줄 정보 목록 UI 추가

- src/api/index.ts
- src/api/schedule.ts
- src/pages/ScheduleList/ScheduleList.page.tsx
- src/store/schedule.ts
- src/types/dto/schedule.ts
- src/utils/date.ts
- src/utils/string.ts
- 스케줄 목록 api 추가
- 스케줄 정보 api 연동
- 지금 서버에서 주는 응답에 등록 일시, 배포 일시 필드는 없어 임시로 스케줄 일시를 넣어두었고 만약 추가되면 변경할 예정입니다.
- 신규 기능 추가
> 스케줄 목록 api 연동

- src/App.tsx
- src/assets/svg/time-16.svg
- src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
- src/components/Schedule/ContentTemplate/ContentTemplate.component.tsx
- src/components/Schedule/ContentTemplate/ContentTemplate.styled.ts
- src/components/Schedule/ContentTemplate/index.ts
- src/components/Schedule/ScheduleTemplate/ScheduleTemplate.component.tsx
- src/components/Schedule/ScheduleTemplate/ScheduleTemplate.styled.ts
- src/components/Schedule/ScheduleTemplate/index.ts
- src/components/Schedule/SessionTemplate/SessionTemplate.component.tsx
- src/components/Schedule/SessionTemplate/SessionTemplate.styled.ts
- src/components/Schedule/SessionTemplate/index.ts
- src/components/Schedule/index.ts
- src/components/common/Input/Input.component.tsx
- src/components/common/Input/Input.styled.ts
- src/components/common/Layout/Layout.component.tsx
- src/components/common/Select/Select.component.tsx
- src/components/common/Select/Select.styled.ts
- src/components/fields/SelectField/SelectField.component.tsx
- src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
- src/pages/CreateSchedule/CreateSchedule.page.tsx
- src/pages/CreateSchedule/CreateSchedule.styled.ts
- src/pages/index.ts
- src/types/dto/index.ts
- src/types/dto/schedule.ts
- src/utils/format.ts
- src/utils/index.ts
- SelectField 컴포넌트에 onChagne 옵션 추가해서 react-hook-form 사용할 수 있또록 추가
- Input endIcon 옵션 추가
- 이떄문에 기존에 input, icon을 감쌀 wrapper가 필요해졌고 에러, disabled, hover, focus 등 액션이 해당 DOM요소로 옮겨졌습니다.
- react-hook-form을 통해 스케쥴 등록 ui 추가
- ScheduleTemplate > SessionTemplate > ContentTemplate 순으로 호출합니다.
- 자세한 내용은 api swagger를 참고해보시면 확인하실 수 있습니다.
- 신규 기능 추가
> 스케줄 생성 UI 추가

- src/components/Generation/GenerationSelect/GenerationSelect.component.tsx
- src/pages/ApplicationFormList/ApplicationFormList.page.tsx
- src/pages/ApplicationList/ApplicationList.page.tsx
- 지원서에 기수 정보 추가하면서 기수 정보 변경될 떄 page 정보 초기화 하는 로직이 들어갔는데 요게 렌더링떄 한번 실행되어서 뒤로가기 할 떄 마다 실행되므로 기수 선택 모달에서 변경할 때 초기화 하도록 수정하였습니다.
- 버그 수정
> 뒤로가기 했을 때 페이징 정보 유지되지 않는 버그 수정

- src/api/schedule.ts
- src/pages/ScheduleDetail/ScheduleDetail.page.tsx
- src/pages/UpdateSchedule/UpdateSchedule.page.tsx
- src/styles/themes/button.ts
- Button 컴포넌트의 primaryLine disabled일 때 스타일이 이상해서 수정
- 스케줄 배포, 배포 취소 가능하게 추가
- 스케줄이 배포되어있으면 수정, 삭제는 불가능 해야함
- 스케줄 배포 되어있을 떄 수정 페이지 접근시 에러 토스트와 함꼐 리다이렉트 로직 추가
- 신규 기능 추가
- 버그 수정
> 스케줄 배포, 배포 취소 가능하게 추가

- src/pages/FaqPage/FaqPage.page.tsx
- src/pages/UpdatePlatformRecruit/UpdatePlatformRecruit.page.tsx
- myTeamName 대소문자 조건이 달라 `iOS`가 셀렉트 되지 않는 문제를 수정
- 자주묻는질문 페이지의 스태프 조건에 브랜딩 계정 추가
- 버그 수정
> Release/1.2.1 Hotfix

- src/App.tsx
- src/components/common/LNB/LNB.component.tsx
- src/components/common/Navigation/Navigation.component.tsx
- src/store/login.ts
- 계정 목록은 마스터 계정만 접근 가능하도록 작업
- 마스터 계정 여부 확인
- 마스터 계정만 접근 가능한 메뉴 확인
- 신규 기능 추가
> 계정 목록은 마스터 계정만 접근 가능하도록 작업

- src/components/Schedule/ScheduleTemplate/ScheduleTemplate.component.tsx
- src/components/ScheduleDetail/ScheduleInfoList/ScheduleInfoList.component.tsx
- src/types/dto/schedule.ts
- src/utils/schedule.ts
placeName이 없는 경우에 대응하기 위한 서버 키값 변경 및 각 키의 용도 변경에 대한 대응
- address(도로주소, 상세주소) -> roadAddress(도로주소)
- placeName(장소명) -> detailAddress(장소명, 상세주소)
- 리팩토링
- 버그 수정
> 스케줄 주소 키값 변경 대응

- src/components/Schedule/ScheduleTemplate/ScheduleTemplate.component.tsx
- src/components/ScheduleDetail/ScheduleInfoList/ScheduleInfoList.component.tsx
- src/components/common/TeamNavigationTabs/TeamNavigationTabs.component.tsx
- src/components/common/TeamNavigationTabs/TeamNavigationTabs.styled.ts
- src/pages/ScheduleDetail/ScheduleDetail.page.tsx
- src/pages/ScheduleList/ScheduleList.page.tsx
- src/types/dto/schedule.ts
- src/utils/schedule.ts
- 플랫폼별 스케줄 추가 및 수정 작업
- 마스터계정의 경우, 모든 플랫폼 스케줄 추가 및 수정 가능
- 플랫폼계정의 경우, 속한 플랫폼만 스케줄 추가 및 수정 가능
- 신규 기능 추가
> 플랫폼별 스케줄 추가 및 수정

- src/components/Schedule/ScheduleTemplate/ScheduleTemplate.component.tsx
- src/components/ScheduleDetail/ScheduleInfoList/ScheduleInfoList.component.tsx
- src/utils/schedule.ts
- 모든 스케줄에 공지 추가 기능 작업
- 신규 기능 추가
> 모든 스케줄에 공지 추가 작업

- src/api/adminMember.ts
- src/components/modal/CreateHelperAdminMemberDialog/CreateHelperAdminMemberDialog.component.tsx
- iOS, Web, Android ... 형태의 문자열에 대해 `String.prototype.toLocaleUpperCase()`를 적용한 결과를 `"${platform}_ HELPER"`로 변환 후 요청에 전달하면서, 서버 에러가 발생하여 iOS 팀에 대해서만 원본 문자열을 그대로 전달하도록 대응합니다.
- 버그 수정
> 헬퍼 생성 시 문자열 변환 로직 이슈 해결
